export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';

export const DETECT_MODERATOR_STATUS = 'DETECT_MODERATOR_STATUS';
export const DETECT_MODERATOR_STATUS_SUCCESS = 'DETECT_MODERATOR_STATUS_SUCCESS';
export const DETECT_MODERATOR_STATUS_ERROR = 'DETECT_MODERATOR_STATUS_ERROR';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_ERROR = 'UPDATE_SETTINGS_SUCCESS';

export const TOGGLE_ANNOUNCEMENTS = 'TOGGLE_ANNOUNCEMENTS';
export const TOGGLE_ANNOUNCEMENTS_SUCCESS = 'TOGGLE_ANNOUNCEMENTS_SUCCESS';
export const TOGGLE_ANNOUNCEMENTS_ERROR = 'TOGGLE_ANNOUNCEMENTS_ERROR';

export const JOIN_CHANNEL = 'JOIN_CHANNEL';
export const JOIN_CHANNEL_SUCCESS = 'JOIN_CHANNEL_SUCCESS';
export const JOIN_CHANNEL_ERROR = 'JOIN_CHANNEL_ERROR';

export const LEAVE_CHANNEL = 'LEAVE_CHANNEL';
export const LEAVE_CHANNEL_SUCCESS = 'LEAVE_CHANNEL_SUCCESS';
export const LEAVE_CHANNEL_ERROR = 'LEAVE_CHANNEL_ERROR';

export const ADVERTISE_ONCE = 'ADVERTISE_ONCE';
export const ADVERTISE_ONCE_STATUS_SUCCESS = 'ADVERTISE_ONCE_STATUS_SUCCESS';
export const ADVERTISE_ONCE_STATUS_ERROR = 'ADVERTISE_ONCE_STATUS_ERROR';
